version: "3.1"

services:

    mongodb70:
        image: mongo:7.0.2
        container_name: mongo_70
        restart: always
        ports:
            - '27019:27017'
        volumes:
            - ../docker_db/mongo7:/data/db

    osint3:
        build: .
        image: osint:3.0
        container_name: osint_v3.0        
        links:
            - mongodb70
        restart: always
        ports:
            - 4200:4200
            - 3000:3000


